# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c7d8e9f0-1a2b-3c4d-5e6f-7a8b9c0d1e2f";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:3" "ssd" "noatime" "space_cache=v2" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/f2e3d4c5-b6a7-9081-7263-5445362718f0";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/c7d8e9f0-1a2b-3c4d-5e6f-7a8b9c0d1e2f";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd:3" "ssd" "noatime" "space_cache=v2" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/c7d8e9f0-1a2b-3c4d-5e6f-7a8b9c0d1e2f";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:3" "ssd" "noatime" "space_cache=v2" ];
    };

  fileSystems."/log" =
    { device = "/dev/disk/by-uuid/c7d8e9f0-1a2b-3c4d-5e6f-7a8b9c0d1e2f";
      fsType = "btrfs";
      options = [ "subvol=@log" "compress=zstd:3" "ssd" "noatime" "space_cache=v2" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E1F2-A3B4";
      fsType = "vfat";
      options = [ "umask=0077" ];
    };

  # Secondary NVMe drive — fill in UUID after formatting
  fileSystems."/mnt/storage" = {
    device = "/dev/disk/by-uuid/d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a";
    fsType = "btrfs";
    options = [ "nofail" "x-systemd.automount" "compress=zstd:3" "ssd" "noatime" "space_cache=v2" ];
  };

  # --- Archived: replaced secondary drive (disconnected) ---
  # fileSystems."/mnt/storage" = {
  #   device = "/dev/disk/by-uuid/00000000-0000-0000-0000-000000000000";
  #   fsType = "btrfs";
  #   options = [ "nofail" "x-systemd.automount" "compress=zstd:3" "ssd" "noatime" "space_cache=v2" ];
  # };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.<yourInterface>.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
